### ISSUE TITLE
Automatic releases

### ISSUE THREAD

**Issue by dragonDScript** [AndresMorelos/developer-utils-app#8]
Making releases manually is boring and makes you and your team lose time. Hence, my feature request woud be to implement weekly releases (canary releases). I can contribute this if you find it hard / or not important.

Would you merge a PR that does this?

**Comment by AndresMorelos** [comment]
@dragonDScript Actually, This repo has a GitHub action that makes the release and creates a draft on every push to the master branch.

Also, this project has an auto-update feature that works for Windows & Linux, but I need to enroll in the Apple developer program to get a certificate and sign the app to make the Mac auto-update works.

But, If you have a better idea to implement it write a comment, I will be happy to discuss it

**Comment by dragonDScript** [comment]
> @dragonDScript Actually, This repo has a GitHub action that makes the release and creates a draft on every push to the master branch.
> 
> Also, this project has an auto-update feature that works for Windows & Linux, but I need to enroll in the Apple developer program to get a certificate and sign the app to make the Mac auto-update works.
> 
> But, If you have a better idea to implement it write a comment, I will be happy to discuss it

I will look into that Action, thank you for answering!
