### ISSUE TITLE
Unix time decoder should use the standard ISO format

### ISSUE THREAD

**Issue by dragonDScript** [AndresMorelos/developer-utils-app#9]
Right now, the Unix time decoder converts the date to this format (if I'm not wrong) MM/DD/YYYY which is a nice format, but it isn't used globally (it is only used in America) and can lead to confusion. For example, here in Europe we use DD/MM/YYYY or DD-MM-YY.

My suggestion would be to instead use the ISO 8601 standard- which is known all around the earth:
YYYY-MM-DD (e.g 2020-12-1).

In this example I used dates, but hours are affected as well.

E.g. this format is not well known on most countries (afaik) mm' ss"
But this is well known in the entire world: hh:mm:ss,ss

**Comment by dragonDScript** [comment]
More information about ISO 8601 [here](https://es.wikipedia.org/wiki/ISO_8601).

**Comment by AndresMorelos** [comment]
@dragonDScript You are totally right, I will be implementing this change for the next minor version.

**Comment by AndresMorelos** [comment]
@dragonDScript It has been implemented in version 1.4.2
